/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'pundarika' at '10/25/16 10:59 AM' with Gradle 2.14.1
 *
 * @author pundarika, @date 10/25/16 10:59 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
